describe("is.utf8", function()
	local t, is
	setup(function()
    t = require "t"
    is = t.is
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(is.utf8))
  end)
  it("positive", function()
    assert.is_true(is.utf8('сайт.рф'))
    assert.is_true(is.utf8('xxx.сайт.рф'))
    assert.is_true(is.utf8('любой.сайт.рф'))
  end)
  it("negative", function()
    assert.is_nil(is.utf8('com'))
    assert.is_nil(is.utf8('SiTe.info'))
  end)
  it("nil", function()
    assert.is_nil(is.utf8(nil))
    assert.is_nil(is.utf8())
  end)
end)