name: publish
on:
  push:
    branches:
      - main
    paths:
      - '**publish.yml'
      - '**.rockspec'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ROCKSPEC: ${{ github.event.repository.name }}-scm-0.rockspec
      LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
    steps:
    - uses: actions/checkout@master
    - name: system dependencies
      run: sudo apt-get update && sudo apt-get upgrade -y
    - uses: jkl1337/gh-actions-lua@v11
      with:
        luaVersion: "5.1.5"
    - uses: jkl1337/gh-actions-luarocks@v5
    - name: install upload deps
      run: luarocks install lua-cjson && luarocks install luasec
    - name: publish
      run: luarocks upload --force --api-key=${{ env.LUAROCKS_API_KEY }} ${{ env.ROCKSPEC }}
